### ISSUE TITLE
Suggestion: Add `asProxyTypeOf2 :: f a -> Proxy a -> f a`.

### ISSUE THREAD

**Issue by ppetr** [ekmett/tagged#12]
Recently I needed
```haskell
asProxyTypeOf2 :: f a -> proxy a -> f a
asProxyTypeOf2 = const
```
to create an empty map with an explicit type. I don't know if such a use case is frequent enough to justify adding a library function for it ...

**Comment by ekmett** [comment]
Given that proxy moved into base, I don't think we're going to get it now, and such requests probably belong as libraries@ proposals.
