### ISSUE TITLE
Port 'pr' and 'pr1' from Frames.

### ISSUE THREAD

**Issue by ekmett** [ekmett/tagged#21]
A brief discursion on the headaches involved:

```
4:47:45 PM <edwardk> ok, shiny new problem
4:47:58 PM <edwardk> i want to port acowley's pr and pr1 template haskell quasi-quoters from Frames to 'tagged'
4:48:05 PM <edwardk> this introduces a problem
4:48:13 PM <edwardk> i can't actually use the TemplateHaskell extension in that package
4:48:22 PM <edwardk> if i do, i have to give up support for stage1 builds
4:48:54 PM <edwardk> so i want to do what glguy did in lens, which is use the packageKey on 7.10+ and the package name and version to hand-craft the reference to the variable
4:48:58 PM <edwardk> for Proxy
4:49:01 PM <edwardk> but this gets complicated
4:49:23 PM <edwardk> because 'base' exports Proxy, on modern GHCs, not 'tagged'
4:49:34 PM <edwardk> so i need to get the package key for 'base' to craft such a reference
```

**Comment by ekmett** [comment]
These should also be extended to produce patterns and types.

**Comment by dmcclean** [comment]
Hmm. I came here to chip in on this, since it was a great idea, but given that I don't know what a stage-1 build is (part of using old-GHC to build new-GHC?) or how what patterns these should be extended to produce, maybe I am better off watching.

**Comment by ekmett** [comment]
Rough explanation without too much lying:

When you build GHC it first builds the compiler quickly, (stage1) then uses it to optimize itself (stage2). 

Some platforms only have stage1 builds.

This has some consequences:

* {-# ANN #-} pragmas don't work on them.
* The TemplateHaskell extension doesn't work. (The `template-haskell` package on the other hand, links fine, you just can't use it.)

Since the TemplateHaskell extension doesn't work we have to jump through some hoops to write splices. Normally we can use ''Foo and the like in the module that makes the TH quasiquoter or combinator the user will use, to avoid dependencies on what definitions are in scope at the use-site.

But ''Foo notation requires {-# LANGUAGE TemplateHaskell #-}

**Comment by dmcclean** [comment]
Ah, so instead of `'Proxy` and `''Proxy` we need `lookupValueName "Data.Proxy.Proxy"`, and so forth? But that looks up the name in the scope of the splice, so it could actually go to some other type if you had suitably wacky imports? And so we need to go through hoops to make the `NameG` that we want?

Does this mean we'd be better off moving the quasiquoters to another package? (Another module isn't far enough away to fix the problem, if I understand it.)

**Comment by ekmett** [comment]
Actually we need to do more evil things than that in lens. =)

https://github.com/ekmett/lens/blob/master/src/Control/Lens/Internal/TH.hs#L110

That said, I'd prefer to bundle it here. Lots of separate packages makes my life harder in the long run, and ensures that little known features like this just never get discovered at all. Discoverability takes a nosedive.

**Comment by ekmett** [comment]
Anyways, it turns out this is a lot easier, because we only have to deal with one version of `base`, so we don't need the full package key or version number to disambiguate base.

**Comment by ekmett** [comment]
This is implemented and seems to work now.
