### ISSUE TITLE
Doesn't work with GHC 8.6

### ISSUE THREAD

**Issue by ndmitchell** [ekmett/tagged#45]
I get:

```
rejecting: tagged-0.8.4, tagged-0.8.3 (conflict:
template-haskell==2.14.0.0/installed-2.1..., tagged => template-haskell>=2.8
&& <2.12)
```

Looks like a bounds bump is required for template-haskell, at the very least.

**Comment by RyanGlScott** [comment]
I've uploaded [`tagged-0.8.6`](http://hackage.haskell.org/package/tagged-0.8.6) (with the upper version bounds bumped) to Hackage.

**Comment by ndmitchell** [comment]
Thanks!!!
