### ISSUE TITLE
Support for ghc-9.4

### ISSUE THREAD

**Issue by jneira** [ekmett/tagged#54]
Hi, trying to build the package with ghc-9.4 throws a solver error due to a template-haskell upper bound:

```
PS D:\dev\ws\haskell\cabal> D:\ghcup\bin\cabal v2-build -j2 -w ghc-9.4.0.20220623 --builddir=dist-newstyle-validate-ghc-9.4.0.20220623 --project-file=cabal.project.validate.libonly Cabal cabal-testsuite Cabal-tests Cabal-QuickCheck Cabal-tree-diff Cabal-described --dry-run
Resolving dependencies...
cabal-3.6.2.0.exe: Could not resolve dependencies:
[__0] trying: Cabal-3.9.0.0 (user goal)
[__1] trying: text-2.0/installed-2.0 (dependency of Cabal)
[__2] trying: process-1.6.14.0/installed-1.6.14.0 (dependency of Cabal)
[__3] trying: base-4.17.0.0/installed-4.17.0.0 (dependency of Cabal)
[__4] trying: Cabal-QuickCheck-3.9.0.0 (user goal)
[__5] trying: QuickCheck-2.14.2 (dependency of Cabal-QuickCheck)
[__6] trying: Cabal-described-3.9.0.0 (user goal)
[__7] trying: tasty-quickcheck-0.10.2 (dependency of Cabal-described)
[__8] next goal: tagged (dependency of tasty-quickcheck)
[__8] rejecting: tagged-0.8.6.1 (conflict: text =>
template-haskell==2.19.0.0/installed-2.19.0.0, tagged => template-haskell>=2.8
&& <2.19)
....
```

thanks!

**Comment by RyanGlScott** [comment]
Indeed. GHC 9.4 hasn't been released yet, and I generally try to avoid raising version bounds to allow unreleased GHC versions until there's at least a release candidate available. (I've been burned one too many times by raising version bounds prematurely for pre-release versions only to have additional breaking changes sneak in at the last second.)

In the meantime, `tagged` should compile if you pass `--allow-newer=tagged:template-haskell`.

**Comment by RyanGlScott** [comment]
Now that GHC 9.4.1-rc1 is out, I've [revised `tagged-0.8.6.1`](https://hackage.haskell.org/package/tagged-0.8.6.1/revisions/) to allow building with `template-haskell-2.19.*`.
